config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("miner.urls", namespace="miner")),
    path('users/', include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miner/urls.py
from django.urls import path

from miner.apps import MinerConfig
from miner.views import InfoDetailView, get_point

app_name = MinerConfig.name

urlpatterns = [
    path("detail_info/<int:pk>/", InfoDetailView.as_view(), name="detail_info"),
    path("get_point/<int:pk>/", get_point, name="get_point"),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    # Базовый функционал пользователя
    # path("login/", login, name="login"),
]

miner/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {"blank": True, "null": True}


class Info(models.Model):
    user = models.ForeignKey("users.User", verbose_name=_("user"), on_delete=models.CASCADE, related_name="info",
                             **NULLABLE)
    amount = models.IntegerField(verbose_name=_("amount"))
    per_second = models.IntegerField(default=1, verbose_name=_("point_per_second"))

    class Meta:
        verbose_name = _("information")
        verbose_name_plural = _("information")

    def __str__(self):
        return str(self.user)


class Achievement(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("name"))
    task = models.IntegerField(verbose_name=_("task"))
    info = models.ManyToManyField(Info, verbose_name=_("info"), related_name="achievement")

    class Meta:
        verbose_name = _("achievement")
        verbose_name_plural = _("achievements")

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = None

    telegram_id = models.IntegerField(unique=True, verbose_name=_("telegram"))

    USERNAME_FIELD = "telegram_id"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def __str__(self):
        return str(self.telegram_id)

miner/views.py
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from miner.models import Info, Achievement


class InfoDetailView(DetailView):
    """
    Представление детального просмотра информации
    """

    model = Info
    extra_context = {
        "title": "Поинты",
        "description": "Нажимай и прибавляй 1 поинт себе в копилку!",
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["achievements"] = Achievement.objects.order_by("task")
        return context_data


def get_point(request, pk):
    """
    Функция блокировки и разблокировки пользователей сайта
    :param pk:
    """
    info = get_object_or_404(Info, pk=pk)
    info.amount += 1
    info.save()
    return redirect(reverse("miner:detail_info", args=[pk]))

users/views.py
from django.shortcuts import render

# Create your views here.

miner/templates/miner/base.html
<!doctype html>
{% load static %}

<html lang="ru" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <title>Team Planet · Gyropsen</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>

    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
</head>
<body>

<div class="container py-3">
    <header>
        {% include 'miner/includes/inc_main_menu.html' %}
    </header>

    <main>

        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">{{title}}</h1>
            <p class="fs-5 text-body-secondary">{{description}}</p>
        </div>

        {% block content %}
        {% endblock %}
    </main>

    {% include 'miner/includes/inc_footer.html' %}
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>
</html>

miner/templates/miner/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-body-secondary">&copy; 2024–{% now 'Y' %}</small>
        </div>
        <div class="col-6 col-md">
            <h5>О проекте</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none"
                                    href="https://t.me/hozdymvirs">О разработчике</a></li>
                <li class="mb-1"><a class="link-secondary text-decoration-none"
                                    href="https://t.me/hozdymvirs">Контакты</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Техподдержка</h5>
            <ul class="list-unstyled text-small">
                <li class="mb-1"><a class="link-secondary text-decoration-none"
                                    href="https://t.me/hozdymvirs">Телеграм</a></li>
            </ul>
        </div>
    </div>
</footer>

miner/templates/miner/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">

    <a href="#"
       class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <span class="fs-4">Team Planet</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none"
           href="#">Личный кабинет</a>
    </nav>
</div>

miner/templates/miner/info_detail.html
{% extends 'miner/base.html' %}
{% block content %}
<div class="row mb-3 text-center">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">
                    Всего поинтов накоплено: {{object.amount}}
                </h4>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <a href="{% url 'miner:get_point' object.pk %}">
                        <img src="/media/coin-svgrepo-com.svg" width="500" height="500" alt="Пример">
                    </a>
                </div>
            </div>
            <div class="card-footer">
                Поинтов в секунду прибавляется: {{object.per_second}}
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table text-center">
        <thead>
        <tr>
            <th style="width: 22%;">Название</th>
            <th style="width: 34%;">Цель</th>
            <th style="width: 34%;">Выполнено</th>
        </tr>
        </thead>
        {% for achievement in achievements %}
        <tbody>
        <tr>
            <td scope="row">{{achievement.name}}</td>
            <td scope="row">{{achievement.task}}</td>
            <td scope="row">
                {% if object.amount >= achievement.task %}
                Выполнено!
                {% else %}
                Осталось немного!
                {% endif %}
            </td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% endblock %}